config/routes.rb
Patients::Application.routes.draw do
  root :to => 'pages#home'

  get "sessions/new"
  get "pages/home"
  get "pages/contact"

  match '/signup',  :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signin',  :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'

  resources :prescriptions
  resources :patients
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/prescription.rb
# == Schema Information
# Schema version: 20110503114457
#
# Table name: prescriptions
#
#  id            :integer         not null, primary key
#  medicine_name :string(255)
#  dispense_date :date
#  days_supply   :integer
#  patient_id    :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Prescription < ActiveRecord::Base
  belongs_to :patient

  validates_inclusion_of :days_supply, :in => 1..90, :message => "must be between 1 and 90 days"
  validates_presence_of :medicine_name

  def days_taken(days_back)
    (0...days_supply).map do |day|
      day_taken = dispense_date + day
      (day_taken <= Date.today && day_taken >= Date.today - days_back) ? day_taken : nil
    end.compact
  end

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  # GET /prescriptions
  # GET /prescriptions.xml
  def index
    @patient = Patient.find_by_id(params[:patient])
    @prescriptions = @patient ? @patient.prescriptions : Prescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prescriptions }
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.xml
  def show
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prescription }
    end
  end

  # GET /prescriptions/new
  # GET /prescriptions/new.xml
  def new
    @prescription = Prescription.new
    @patient = Patient.find_by_id(params[:patient])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prescription }
    end
  end

  # GET /prescriptions/1/edit
  def edit
    @prescription = Prescription.find(params[:id])
    @patient = Patient.find_by_id(params[:patient])
  end

  # POST /prescriptions
  # POST /prescriptions.xml
  def create
    @prescription = Prescription.create!(params[:prescription])

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to(@prescription, :notice => 'Prescription was successfully created.') }
        format.xml  { render :xml => @prescription, :status => :created, :location => @prescription }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prescription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prescriptions/1
  # PUT /prescriptions/1.xml
  def update
    @prescription = Prescription.find(params[:id])
    respond_to do |format|
      if @prescription.update_attributes(params[:prescription])
        format.html { redirect_to(@prescription, :notice => 'Prescription was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prescription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.xml
  def destroy
    @prescription = Prescription.find(params[:id])
    @patient = @prescription.patient
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to(prescriptions_path(:patient => @patient)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_all.html.erb
<h1>Listing prescriptions</h1>

<table>
  <tr>
    <th>Medicine name</th>
    <th>Dispense date</th>
    <th>Days supply</th>
    <th>Patient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prescriptions.each do |prescription| %>
  <tr id="row_id(prescription.medicine_name)">
    <td><%= prescription.medicine_name %></td>
    <td><%= prescription.dispense_date %></td>
    <td><%= prescription.days_supply %></td>
    <td><%= link_to prescription.patient.name, prescription.patient %></td>
    <td><%= link_to 'Show', prescription %></td>
    <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
    <td><%= link_to 'Delete', prescription, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<p>
  Showing all prescriptions
</p>
<br />

app/views/prescriptions/_all_for_patient.html.erb
<h1><%= "Listing prescriptions for #{@patient.name}"%></h1>

<table>
  <tr>
    <th>Medicine name</th>
    <th>Dispense date</th>
    <th>Days supply</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prescriptions.each do |prescription| %>
  <tr id="<%= row_id(prescription.medicine_name) %>">
    <td><%= prescription.medicine_name %></td>
    <td><%= prescription.dispense_date %></td>
    <td><%= prescription.days_supply %></td>
    <td><%= link_to 'Show', prescription %></td>
    <td><%= link_to 'Edit', edit_prescription_path(prescription, :patient => @patient) %></td>
    <td><%= link_to 'Delete', prescription, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<p>
  <% if @prescriptions %>
    <%= "Showing all #{@prescriptions.length} prescription(s) for "%> 
  <% else %>
    <%= "No prescriptions found for " %>
  <% end %>
  <%= link_to(@patient.name, @patient) %>
</p>
<%= link_to 'Add Prescription', new_prescription_path(:patient => @patient) %>
<br />
<br />

app/views/prescriptions/_form.html.erb
<%= form_for(@prescription) do |f| %>
  <% if @prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @prescription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :medicine_name %><br />
    <%= f.text_field :medicine_name %>
  </div>
  <div class="field">
    <%= f.label :dispense_date %><br />
    <%= f.date_select :dispense_date %>
  </div>
  <div class="field">
    <%= f.label :days_supply %><br />
    <%= f.text_field :days_supply %>
  </div>
  <%= f.hidden_field :patient_id, :value => @patient.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<% if @patient %>
  <%= render 'all_for_patient' %>
<% else %>
  <%= render 'all' %>
<% end %>
<%= link_to "View All Patients", patients_path %>

app/views/prescriptions/new.html.erb
<h1>New Prescription for <%= @patient.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p>
  <b>Medicine name:</b>
  <%= @prescription.medicine_name %>
</p>

<p>
  <b>Dispense date:</b>
  <%= @prescription.dispense_date %>
</p>

<p>
  <b>Days supply:</b>
  <%= @prescription.days_supply %>
</p>

<p>
  <b>Patient:</b>
  <%= @prescription.patient ? link_to(@prescription.patient.name, @prescription.patient) : @prescription.patient %>
</p>


<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'View all', prescriptions_path %>