config/routes.rb
Patients::Application.routes.draw do
  root :to => 'pages#home'

  get "sessions/new"
  get "pages/home"
  get "pages/contact"

  match '/signup',  :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signin',  :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'

  resources :prescriptions
  resources :patients
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/user.rb
# == Schema Information
# Schema version: 20110503122611
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates_presence_of :name
  validates :email, :format => { :with => email_regex},
                    :uniqueness => { :case_sensitive => false}
                    
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
                       
  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
    end

private

  def encrypt_password
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :show]
  before_filter :correct_user, :only => [:edit, :update]

  def new
    @title = "Create Admin Account"
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Your application to become an Admin user was successful"
      redirect_to @user
    else
      @title = "Admin Account"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit details"
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    if @user.save
      flash[:success] = "Your details have been updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def authenticate
    deny_access unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>
  Update details for <%= @user.name %>
</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/users/new.html.erb
<h1>Apply for Admin Account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>
  <%= @user.name %> is an Admin User
</h1>
<% if current_user?(@user) %>
  <p>
    <%= link_to "Change Password", edit_user_path(@user) %>
  </p>
<% end %>