config/routes.rb
Patients::Application.routes.draw do
  root :to => 'pages#home'

  get "sessions/new"
  get "pages/home"
  get "pages/contact"

  match '/signup',  :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signin',  :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'

  resources :prescriptions
  resources :patients
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/patient.rb
# == Schema Information
# Schema version: 20110503114457
#
# Table name: patients
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Patient < ActiveRecord::Base
  has_many :prescriptions

  validates_presence_of :name
  validates_uniqueness_of :name

  def medicines_taken()
    prescriptions.map(&:medicine_name).uniq
  end

  def days_taken(medicine_name, days_back)
    prescriptions.map do |prescription|
      prescription.medicine_name == medicine_name ? prescription.days_taken(days_back) : nil
    end.flatten.compact.uniq
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :authenticate

  # GET /patients
  # GET /patients.xml
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.xml
  def show
    @patient = Patient.find(params[:id])
    @title = @patient.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.xml
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.xml
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to(@patient, :notice => 'Patient was successfully created.') }
        format.xml  { render :xml => @patient, :status => :created, :location => @patient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.xml
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to(@patient, :notice => 'Patient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.xml
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to(patients_url) }
      format.xml  { head :ok }
    end
  end

  private

    def authenticate
      deny_access unless signed_in?
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table class="patient">
  <tr>
    <th>Name</th>
    <th>Prescriptions</th>
  </tr>

<% @patients.each do |patient| %>
  <tr id="<%=row_id(patient) %>">
    <td><%= link_to patient.name, patient %></td>
    <td><%= patient.prescriptions.length %></td>
    <td><%= link_to 'Add Prescription', new_prescription_path(:patient => patient), %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p>
  <b>Name:</b>
  <%= @patient.name %>
</p>
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <% if @patient.medicines_taken.empty?%>
        No medicines taken in the last 90 days.
      <% else %>
        <table class="prescriptions">
          <tr>
          <th>Medicine Name</th><th>Days taken (last 90 days)</th>
          </tr>
        <% @patient.medicines_taken.each do |medicine_name| %>
          <tr id="<%= row_id(medicine_name) %>">
            <td><%= medicine_name %></td><td><%= @patient.days_taken(medicine_name, 90).length %></td>
          </tr>
        <% end %>
        </table>
      <% end %>
      <p>
        <%= link_to "View All Prescriptions", prescriptions_path(:patient => @patient) %>
      </p>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @patient.name %><br />
      <strong>URL</strong>  <%= link_to patient_path(@patient), @patient %>
    </td>
  </tr>
</table>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'All Patients', patients_path %>